//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Step2.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_Step2TYPE                   130
#define ID_ADDFISH_BETAFISH             32771
#define ID_ADDFISH_ANGELFISH            32772
#define ID_ADDFISH_CATFISH              32773
#define ID_FILE_TRASHCAN                32774
#define ID_ADDFISH_TRESURE              32775
#define ID_FILE_SAVEAS                  32776
#define ID_FILE_OPEN32777               32777
#define ID_CARE_FEED                    32778
#define ID_CARE_CLEAN                   32779
#define ID_ADDDECOR_TREASURECHEST       32780
#define ID_ADDDECOR_SPARTYTREASURECHEST 32781
#define ID_COSTS_BETAFISH               32782
#define ID_COSTS_ANGELFISH              32783
#define ID_COSTS_CATFISH                32784
#define ID_COSTS_SPARTYTREASURECHEST    32785
#define ID_RULES_KEEPASMANYFISHALIVEASYOUCAN 32786
#define ID_RULES_POINTSWILLBEGIVENFORFISHALIVE 32787
#define ID_RULES_MOREPOINTSWILLBEGIVENFORMOREEXPENSIVEFISH 32788
#define ID_RULES_BUTTHEYWILLALSODIEFASTERIFNOTTAKENCAREOF 32789
#define ID_RULES_FISHWILLDIEDUETOLACKOFFOOD 32790
#define ID_RULES_TANKWILLALSOGETDIRTYOVERTIME 32791
#define ID_RULES_USERWILLLOSERPOINTSFORFISHDYINGANDTHETANKBECOMINGDIRTY 32792
#define ID_RULES_COSTSFOREACHFISHANDITEMARELISTEDUNDERTHEMENUOPTION 32793
#define ID_RULES_SPARTYTREASURECHESTSWILLRANDOMLYPUTFISHINTHEAQUARIUMPARTOFTHETIME 32794
#define ID_Menu                         32795
#define ID_RULES_                       32796
#define ID_RULES_32797                  32797
#define ID_RULES_IFTHEACIDBUBBLESREACHESTHETOPOFTHEAQUARIUM 32798
#define ID_RULES_ITBURSTSANDDIRTIESTHEAQUARIUM 32799
#define ID_RULES_USERMAYCLICKONTHEBUBBLESBEFORETHEYREACHTHETOPOFTHEAQUARIUMTOSTOPTHEM 32800
#define ID_RULES_32801                  32801
#define ID_RULES_THEGAMEWILLBEOVERWHENTHESCOREBECOMESNEGATIVE 32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
